openapi: 3.0.0
info:
  title: Moderation Service
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /moderation:
    post:
      tags:
        - General
      summary: http://localhost:8080/moderation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                input: >-
                  Hola Putos, Cómo están? puto. Les quiero decir que son unos
                  perros mala agradecidos. Espero que se mueran pronto, son unos
                  hijos de puta Hola putoey, Cómo están? puto. Les quiero decir
                  que son unos perros mala agradecidos. Espero que se mueran
                  pronto, son unos hijos de puta Hola Putos, Cómo están? puto.
                  Les quiero decir que son unos perros mala agradecidos. Espero
                  que se mueran pronto, son unos hijos de puta Hola putoey, Cómo
                  están? puto. Les quiero decir que son unos perros mala
                  agradecidos. Espero que se mueran pronto, son unos hijos de
                  puta Hola Putos, Cómo están? puto. Les quiero decir que son
                  unos perros mala agradecidos. Espero que se mueran pronto, son
                  unos hijos de puta Hola putoey, Cómo están? puto. Les quiero
                  decir que son unos perros mala agradecidos. Espero que se
                  mueran pronto, son unos hijos de puta Hola Putos, Cómo están?
                  puto. Les quiero decir que son unos perros mala agradecidos.
                  Espero que se mueran pronto, son unos hijos de puta Hola
                  putoey, Cómo están? puto. Les quiero decir que son unos perros
                  mala agradecidos. Espero que se mueran pronto, son unos hijos
                  de puta Hola Putos, Cómo están? puto. Les quiero decir que son
                  unos perros mala agradecidos. Espero que se mueran pronto, son
                  unos hijos de puta Hola putoey, Cómo están? puto. Les quiero
                  decir que son unos perros mala agradecidos. Espero que se
                  mueran pronto, son unos hijos de puta Hola Putos, Cómo están?
                  puto. Les quiero decir que son unos perros mala agradecidos.
                  Espero que se mueran pronto, son unos hijos de puta Hola
                  putoey, Cómo están? puto. Les quiero decir que son unos perros
                  mala agradecidos. Espero que se mueran pronto, son unos hijos
                  de puta Hola Putos, Cómo están? puto. Les quiero decir que son
                  unos perros mala agradecidos. Espero que se mueran pronto, son
                  unos hijos de puta Hola putoey, Cómo están? puto. Les quiero
                  decir que son unos perros mala agradecidos. Espero que se
                  mueran pronto, son unos hijos de puta Hola Putos, Cómo están?
                  puto. Les quiero decir que son unos perros mala agradecidos.
                  Espero que se mueran pronto, son unos hijos de puta Hola
                  putoey, Cómo están? puto. Les quiero decir que son unos perros
                  mala agradecidos. Espero que se mueran pronto, son unos hijos
                  de puta Hola Putos, Cómo están? puto. Les quiero decir que son
                  unos perros mala agradecidos. Espero que se mueran pronto, son
                  unos hijos de puta Hola putoey, Cómo están? puto. Les quiero
                  decir que son unos perros mala agradecidos. Espero que se
                  mueran pronto, son unos hijos de puta Hola Putos, Cómo están?
                  puto. Les quiero decir que son unos perros mala agradecidos.
                  Espero que se mueran pronto, son unos hijos de puta Hola
                  putoey, Cómo están? puto. Les quiero decir que son unos perros
                  mala agradecidos. Espero que se mueran pronto, son unos hijos
                  de puta Hola Putos, Cómo están? puto. Les quiero decir que son
                  unos perros mala agradecidos. Espero que se mueran pronto, son
                  unos hijos de puta Hola putoey, Cómo están? puto. Les quiero
                  decir que son unos perros mala agradecidos. Espero que se
                  mueran pronto, son unos hijos de puta Hola Putos, Cómo están?
                  puto. Les quiero decir que son unos perros mala agradecidos.
                  Espero que se mueran pronto, son unos hijos de puta Hola
                  putoey, Cómo están? puto. Les quiero decir que son unos perros
                  mala agradecidos. Espero que se mueran pronto, son unos hijos
                  de puta 
                application_id: test
      parameters:
        - name: disregarded
          in: header
          schema:
            type: boolean
          example: 'true'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
